import sanitizeHtml from "sanitize-html";

/**
 * Sanitizes HTML from user input before rendering via dangerouslySetInnerHTML.
 * Allows tags generated by TipTap editor while stripping dangerous content.
 */
export function sanitizeContent(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: [
      "p", "br", "strong", "b", "em", "i", "u", "s", "del",
      "h1", "h2", "h3", "h4", "h5", "h6",
      "ul", "ol", "li",
      "blockquote", "pre", "code",
      "a", "img",
      "table", "thead", "tbody", "tr", "th", "td",
      "div", "span",
      // TipTap task list
      "input",
    ],
    allowedAttributes: {
      "a": ["href", "target", "rel"],
      "img": ["src", "alt", "width", "height"],
      "input": ["type", "checked", "disabled"],
      "*": ["class", "data-type"],
    },
    allowedSchemes: ["http", "https", "mailto"],
    // Disallow javascript: URLs
    allowedSchemesByTag: {
      "a": ["http", "https", "mailto"],
      "img": ["http", "https", "data"],
    },
    // Force safe rel on links
    transformTags: {
      "a": (tagName, attribs) => ({
        tagName,
        attribs: {
          ...attribs,
          rel: "noopener noreferrer",
          ...(attribs.target === "_blank" ? { target: "_blank" } : {}),
        },
      }),
    },
  });
}
